# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98958a94d65e0b04449994a1c759bfcbdd1b852aeb4eeb39e08df44bbfbedbde08015ab68327dde344ef36719c5b0a8ed83cc0526a55b903e3ad3fbab5845eec

test:
  secret_key_base: ccf3b1dcfb40d145a83867a7078936bba688f98311ca33e11fa18c436d9a4e6d30dd5a72f1a981feadfa3385e202cb9b400364e69ddc0cb39da592d3ca6df362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
